"""Backwards-compatible re-exporter for ``process_improve.multivariate``.

The implementation now lives in :mod:`process_improve.multivariate._pca_pls`
(ENG-23 / #305): the renamed file makes filename-ranked tooling (Jump-to-File,
fuzzy search, codecov reports) less ambiguous about which ``methods.py`` is
being shown.

Every public name remains importable as before::

    from process_improve.multivariate.methods import PCA, PLS, MCUVScaler
"""

from process_improve.multivariate._pca_pls import (
    MBPCA,
    MBPLS,
    PCA,
    PLS,
    REFERENCE_LINE_COLOR,
    TPLS,
    DataFrameDict,
    MCUVScaler,
    Plot,
    Resampler,
    SpecificationWarning,
    center,
    check_random_state,
    coefficient_plot,
    correlation_loadings_plot,
    detect_outliers_esd,
    eigenvalue_summary,
    ellipse_coordinates,
    epsqrt,
    explained_variance_plot,
    hotellings_t2_limit,
    internal_pls_nipals_fit_one_pc,
    loading_plot,
    nan_to_zeros,
    observation_contributions,
    predictions_vs_observed_plot,
    project_variables,
    quick_regress,
    randomization_test_mbpls,
    regress_a_space_on_b_row,
    rv2_coefficient,
    rv_coefficient,
    safe_inverse,
    scale,
    score_limit,
    score_plot,
    spe_calculation,
    spe_limit,
    spe_plot,
    squared_cosine,
    ssq,
    t2_plot,
    terminate_check,
    vip,
)

__all__ = [
    "MBPCA",
    "MBPLS",
    "PCA",
    "PLS",
    "REFERENCE_LINE_COLOR",
    "TPLS",
    "DataFrameDict",
    "MCUVScaler",
    "Plot",
    "Resampler",
    "SpecificationWarning",
    "center",
    "check_random_state",
    "coefficient_plot",
    "correlation_loadings_plot",
    "detect_outliers_esd",
    "eigenvalue_summary",
    "ellipse_coordinates",
    "epsqrt",
    "explained_variance_plot",
    "hotellings_t2_limit",
    "internal_pls_nipals_fit_one_pc",
    "loading_plot",
    "nan_to_zeros",
    "observation_contributions",
    "predictions_vs_observed_plot",
    "project_variables",
    "quick_regress",
    "randomization_test_mbpls",
    "regress_a_space_on_b_row",
    "rv2_coefficient",
    "rv_coefficient",
    "safe_inverse",
    "scale",
    "score_limit",
    "score_plot",
    "spe_calculation",
    "spe_limit",
    "spe_plot",
    "squared_cosine",
    "ssq",
    "t2_plot",
    "terminate_check",
    "vip",
]
