"""Multivariate analysis: PCA, PLS, TPLS, scaling, and diagnostic plots."""

from process_improve.multivariate.methods import (
    OPLS,
    PCA,
    PLS,
    TPLS,
    AdaptivePCA,
    AdaptivePLS,
    MCUVScaler,
    center,
    eigenvalue_summary,
    observation_contributions,
    project_variables,
    rv2_coefficient,
    rv_coefficient,
    scale,
    spe_contributions,
    squared_cosine,
    t2_contributions,
    vip,
)
from process_improve.multivariate.plots import (
    coefficient_plot,
    correlation_loadings_plot,
    explained_variance_plot,
    loading_plot,
    predictions_vs_observed_plot,
    score_plot,
    spe_plot,
    t2_plot,
)

__all__ = [
    "OPLS",
    "PCA",
    "PLS",
    "TPLS",
    "AdaptivePCA",
    "AdaptivePLS",
    "MCUVScaler",
    "center",
    "coefficient_plot",
    "correlation_loadings_plot",
    "eigenvalue_summary",
    "explained_variance_plot",
    "loading_plot",
    "observation_contributions",
    "predictions_vs_observed_plot",
    "project_variables",
    "rv2_coefficient",
    "rv_coefficient",
    "scale",
    "score_plot",
    "spe_contributions",
    "spe_plot",
    "squared_cosine",
    "t2_contributions",
    "t2_plot",
    "vip",
]
