"""Generate the static PNGs for the process-monitoring chapter of the PID book.

Three figures are produced, replacing images previously generated by R
scripts (``explain-CUSUM.R``, ``explain-EWMA.R``) whose seed could not be
reproduced by readers working in Python:

- ``demo-of-monitoring-chart.png``: the introductory monitoring chart with a
  target, control limits, and a drift out of control near the end.
- ``explain-CUSUM.png``: four stacked panels; an in-control series and its
  CUSUM (with a V-mask), then the same series with a 0.4 sigma shift at
  t = 150 and its CUSUM (with a V-mask).
- ``explain-EWMA.png``: five stacked panels; the shifted raw data as a
  Shewhart chart of individual values, EWMA charts with lambda = 0.8, 0.4
  and 0.1, and a CUSUM chart, for a 1 sigma shift at t = 150.

The data are seeded (``SEED_EXPLAIN`` and ``SEED_DEMO``) and match the
inline Plotly code blocks in the chapter, so a reader running the chapter
code sees the same numbers as the committed PNGs.

Usage
-----
    python scripts/monitoring_chapter_figures.py [output_dir]

Writes the three PNGs into ``output_dir``, by default the current
directory. Point ``output_dir`` at ``figures/monitoring/`` in a checkout of
the figures repository to refresh the committed images.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np

# Shared settings for the two explainer figures; these values are quoted in
# the chapter prose, so change them only together with the book text.
SEED_EXPLAIN = 17
N_POINTS = 201
MU = 20.0
SIGMA = 3.0
SHIFT_AT = 150
CUSUM_SHIFT_FRACTION = 0.4  # a 1.2 unit shift: almost invisible in raw data
EWMA_SHIFT_FRACTION = 1.0  # a 3 unit shift: visible to the EWMA chart

# Settings for the introductory demonstration chart. These keep the
# character of the original figure: a tank temperature (tag TC241)
# around 10 degC, in control for 150 samples, then a slow upward
# drift that ends beyond the upper control limit.
SEED_DEMO = 0
DEMO_N = 200
DEMO_TARGET = 10.0
DEMO_SD = 1.5
DEMO_DRIFT_FROM = 150
DEMO_DRIFT_STEP = 0.09

DPI = 300


def ewma(x: np.ndarray, lam: float, target: float) -> np.ndarray:
    """Return the EWMA statistic (filter form) for a series.

    Parameters
    ----------
    x : np.ndarray
        The raw time series.
    lam : float
        The EWMA weight, between 0 and 1, applied to the newest value.
    target : float
        The starting value for the recursion.

    Returns
    -------
    np.ndarray
        The smoothed series, the values plotted on an EWMA chart.
    """
    y = np.zeros(len(x))
    previous = target
    for k in range(len(x)):
        y[k] = lam * x[k] + (1 - lam) * previous
        previous = y[k]
    return y


def make_series() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return the base, CUSUM-shifted, and EWMA-shifted series.

    Returns
    -------
    tuple[np.ndarray, np.ndarray, np.ndarray]
        The in-control series, the series with a 0.4 sigma shift from
        ``SHIFT_AT`` onward, and the series with a 1 sigma shift from
        ``SHIFT_AT`` onward.
    """
    rng = np.random.default_rng(SEED_EXPLAIN)
    base = rng.normal(MU, SIGMA, N_POINTS)
    data_cusum = base.copy()
    data_cusum[SHIFT_AT:] += CUSUM_SHIFT_FRACTION * SIGMA
    data_ewma = base.copy()
    data_ewma[SHIFT_AT:] += EWMA_SHIFT_FRACTION * SIGMA
    return base, data_cusum, data_ewma


# V-mask design parameters. The arm slope equals the tabular CUSUM
# reference value K (half the shift to detect: 0.5 * 0.4 sigma = 0.6
# units per sample) and the mask half-width at the newest point equals
# the decision interval H (5 sigma = 15 units). See the CUSUM section of
# the chapter for the tabular equivalents.
VMASK_K = 0.5 * CUSUM_SHIFT_FRACTION * SIGMA
VMASK_H = 5 * SIGMA
VMASK_SPAN = 60


def draw_v_mask(ax: plt.Axes, s: np.ndarray, anchor: int) -> None:
    """Draw a designed V-mask on a CUSUM axis, anchored at sample ``anchor``.

    The apex sits a lead distance ``H / K`` ahead of the anchor and the two
    arms open backwards with slope ``K`` per sample, so the mask half-width
    at the anchor is exactly ``H``. A short vertical bar marks the anchor.
    A prior point crossing an arm signals a shift.

    Parameters
    ----------
    ax : plt.Axes
        The axis holding the CUSUM trace.
    s : np.ndarray
        The CUSUM values plotted on that axis.
    anchor : int
        The sample number (usually the newest) the mask is anchored at.
    """
    apex_x, apex_y = anchor + VMASK_H / VMASK_K, s[anchor]
    tail_x = anchor - VMASK_SPAN
    tail_half_width = VMASK_K * (apex_x - tail_x)
    for sign in (-1.0, 1.0):
        ax.plot([apex_x, tail_x], [apex_y, apex_y + sign * tail_half_width], color="red", lw=2)
    ax.plot([anchor, anchor], [apex_y - VMASK_H, apex_y + VMASK_H], color="red", lw=2)


def figure_cusum(base: np.ndarray, data_cusum: np.ndarray, out: pathlib.Path) -> None:
    """Write ``explain-CUSUM.png``: raw and CUSUM panels, without and with a shift.

    Parameters
    ----------
    base : np.ndarray
        The in-control series.
    data_cusum : np.ndarray
        The series with a 0.4 sigma shift at ``SHIFT_AT``.
    out : pathlib.Path
        Directory the PNG is written into.
    """
    s_base = np.cumsum(base - MU)
    s_shift = np.cumsum(data_cusum - MU)
    # Leave room for the V-mask arms: they reach anchor value +/- (H + K * span)
    # at the tail, and the apex sits a lead distance H / K past the anchor.
    arm_reach = VMASK_H + VMASK_K * VMASK_SPAN
    anchored = (s_base[-1], s_shift[-1])
    ylim = (
        min(s_base.min(), s_shift.min(), min(anchored) - arm_reach) - 5,
        max(s_base.max(), s_shift.max(), max(anchored) + arm_reach) + 5,
    )
    xlim = (-5, N_POINTS - 1 + VMASK_H / VMASK_K + 5)

    fig, axes = plt.subplots(4, 1, figsize=(10, 12.5))
    axes[0].plot(base, ".", color="black")
    axes[0].axhline(MU, color="grey", lw=0.8)
    axes[0].set_title("Case 1, raw data: no shift in mean")

    axes[1].plot(s_base, "-o", ms=3, color="black")
    axes[1].axhline(0, color="grey", lw=0.8)
    axes[1].set_ylim(ylim)
    axes[1].set_xlim(xlim)
    axes[1].set_title("Case 1: S(t), with the V-mask on the newest point: all points inside the arms")
    draw_v_mask(axes[1], s_base, anchor=N_POINTS - 1)

    shift_size = CUSUM_SHIFT_FRACTION * SIGMA
    axes[2].plot(data_cusum, ".", color="black")
    axes[2].axhline(MU, color="grey", lw=0.8)
    axes[2].set_title(f"Case 2, a shift of {shift_size:g} units ({CUSUM_SHIFT_FRACTION} sigma) at t={SHIFT_AT}")

    axes[3].plot(s_shift, "-o", ms=3, color="black")
    axes[3].axhline(0, color="grey", lw=0.8)
    axes[3].set_ylim(ylim)
    axes[3].set_xlim(xlim)
    axes[3].set_title("Case 2: S(t): points cross the lower arm of the V-mask, signalling the shift")
    axes[3].set_xlabel("Time steps")
    draw_v_mask(axes[3], s_shift, anchor=N_POINTS - 1)

    fig.tight_layout()
    fig.savefig(out / "explain-CUSUM.png", dpi=DPI)
    plt.close(fig)


def figure_ewma(data_ewma: np.ndarray, out: pathlib.Path) -> None:
    """Write ``explain-EWMA.png``: Shewhart, three EWMA charts, and a CUSUM.

    Parameters
    ----------
    data_ewma : np.ndarray
        The series with a 1 sigma shift at ``SHIFT_AT``.
    out : pathlib.Path
        Directory the PNG is written into.
    """
    fig, axes = plt.subplots(5, 1, figsize=(10, 15))

    lcl, ucl = MU - 3 * SIGMA, MU + 3 * SIGMA
    axes[0].plot(data_ewma, "-", color="black", lw=0.9)
    axes[0].axhline(MU, color="grey", lw=0.8)
    axes[0].axhline(lcl, color="red")
    axes[0].axhline(ucl, color="red")
    axes[0].axvline(SHIFT_AT, color="darkblue", ls="--")
    axes[0].set_title("Raw data (and also a Shewhart monitoring chart; limits at 3 sigma)")

    for ax, lam in zip(axes[1:4], (0.8, 0.4, 0.1), strict=True):
        half_width = 3 * SIGMA * np.sqrt(lam / (2 - lam))
        ax.plot(ewma(data_ewma, lam, MU), "-", color="black", lw=0.9)
        ax.axhline(MU, color="grey", lw=0.8)
        ax.axhline(MU - half_width, color="red")
        ax.axhline(MU + half_width, color="red")
        ax.axvline(SHIFT_AT, color="darkblue", ls="--")
        ax.set_title(f"EWMA with lambda = {lam}")

    s_shift = np.cumsum(data_ewma - MU)
    axes[4].plot(s_shift, "-", color="black", lw=0.9)
    axes[4].axhline(0, color="grey", lw=0.8)
    axes[4].axvline(SHIFT_AT, color="darkblue", ls="--")
    axes[4].set_title("CUSUM")
    axes[4].set_xlabel("Time steps")

    fig.tight_layout()
    fig.savefig(out / "explain-EWMA.png", dpi=DPI)
    plt.close(fig)


def figure_demo(out: pathlib.Path) -> None:
    """Write ``demo-of-monitoring-chart.png``: the introductory chart.

    Parameters
    ----------
    out : pathlib.Path
        Directory the PNG is written into.
    """
    rng = np.random.default_rng(SEED_DEMO)
    series = rng.normal(DEMO_TARGET, DEMO_SD, DEMO_N)
    n_drift = DEMO_N - DEMO_DRIFT_FROM
    series[DEMO_DRIFT_FROM:] += np.arange(n_drift) * DEMO_DRIFT_STEP
    ucl, lcl = DEMO_TARGET + 3 * DEMO_SD, DEMO_TARGET - 3 * DEMO_SD

    fig, ax = plt.subplots(figsize=(12, 4))
    ax.plot(series, "-", color="black", lw=1.2)
    ax.axhline(DEMO_TARGET, color="grey", ls=":")
    ax.axhline(ucl, color="red")
    ax.axhline(lcl, color="red")
    ax.text(2, ucl + 0.25, "UCL", fontsize=12)
    ax.text(2, lcl + 0.25, "LCL", fontsize=12)
    ax.set_title("Tank temperature, TC241 [degC]")
    ax.set_xlabel("Time sequence order")
    ax.set_ylabel("TC241 [degC]")
    fig.tight_layout()
    fig.savefig(out / "demo-of-monitoring-chart.png", dpi=DPI)
    plt.close(fig)


def main() -> None:
    """Generate all three chapter figures into the output directory."""
    out = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path()
    out.mkdir(parents=True, exist_ok=True)
    base, data_cusum, data_ewma = make_series()
    figure_cusum(base, data_cusum, out)
    figure_ewma(data_ewma, out)
    figure_demo(out)


if __name__ == "__main__":
    main()
